function wtb
    # Wrapper for worktree-bench switch (keep behavior/comments in sync with scripts/wtb.bash).
    set -l args $argv
    set -l directive_file (mktemp)

    env WTB_DIRECTIVE_FILE=$directive_file worktree-bench switch $args
    set -l exit_code $status

    if test -s "$directive_file"
        # Directive lines (cd) are generated by worktree-bench; keep formats in sync.
        eval (cat "$directive_file" | string collect)
        if test $exit_code -eq 0
            set exit_code $status
        end
    end

    rm -f "$directive_file"
    return $exit_code
end
