function wtb
    # Wrapper for worktree-bench (keep behavior/comments in sync with scripts/wtb.bash).
    set -l args $argv
    set -l directive_file (mktemp)

    set -l bin worktree-bench
    if test -n "$WTB_BIN"
        set bin $WTB_BIN
    else
        set -l repo_root (git rev-parse --show-toplevel 2>/dev/null)
        if test -n "$repo_root"; and test -x "$repo_root/worktree-bench"
            set bin "$repo_root/worktree-bench"
        end
    end

    env WTB_DIRECTIVE_FILE=$directive_file $bin $args
    set -l exit_code $status

    if test -s "$directive_file"
        # Directive lines (cd) are generated by worktree-bench; keep formats in sync.
        eval (cat "$directive_file" | string collect)
        if test $exit_code -eq 0
            set exit_code $status
        end
    end

    rm -f "$directive_file"
    return $exit_code
end
